import Foundation

/// Transcripts from Supadata (https://supadata.ai): a paid, supported alternative to scraping
/// YouTube's caption tracks. Configure `SUPADATA_API_KEY` (Config/Secrets.xcconfig).
struct SupadataTranscriptProvider: TranscriptProvider {
    nonisolated static let apiKeyPlistKey = "SUPADATA_API_KEY"
    nonisolated static let endpoint = URL(string: "https://api.supadata.ai/v1/youtube/transcript")!

    var apiKey: String
    var preferredLanguage = "en"
    /// Cues are merged into lines of roughly this many seconds, like the caption path.
    var secondsPerLine: Double = 8
    var session: URLSession = {
        let config = URLSessionConfiguration.default
        config.timeoutIntervalForRequest = 60
        return URLSession(configuration: config)
    }()

    static func fromInfoPlist(_ bundle: Bundle = .main) -> SupadataTranscriptProvider? {
        guard let key = (bundle.object(forInfoDictionaryKey: apiKeyPlistKey) as? String)?
                .trimmingCharacters(in: .whitespacesAndNewlines), !key.isEmpty else { return nil }
        return SupadataTranscriptProvider(apiKey: key)
    }

    func transcript(for videoID: String) async throws -> FetchedTranscript {
        var components = URLComponents(url: Self.endpoint, resolvingAgainstBaseURL: false)!
        components.queryItems = [
            URLQueryItem(name: "url", value: YouTubeLink.watchURL(for: videoID).absoluteString),
            URLQueryItem(name: "lang", value: preferredLanguage),
            URLQueryItem(name: "text", value: "false"),
        ]
        var request = URLRequest(url: components.url!)
        request.setValue(apiKey, forHTTPHeaderField: "x-api-key")
        request.setValue("application/json", forHTTPHeaderField: "Accept")

        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await session.data(for: request)
        } catch {
            throw RecipeSourceError.transcriptUnavailable("Supadata: \(error.localizedDescription)")
        }
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard status == 200 else {
            throw RecipeSourceError.transcriptUnavailable("Supadata HTTP \(status): \(Self.errorMessage(from: data))")
        }
        let payload: Payload
        do { payload = try JSONDecoder().decode(Payload.self, from: data) }
        catch { throw RecipeSourceError.transcriptUnavailable("Supadata sent an answer this app doesn't understand: \(error.localizedDescription)") }

        let lines = Self.lines(from: payload.content, secondsPerLine: secondsPerLine)
        guard !lines.isEmpty else { throw RecipeSourceError.transcriptUnavailable("Supadata has no transcript for this video") }
        let end = payload.content.map { ($0.offset + ($0.duration ?? 0)) / 1000 }.max()
        return FetchedTranscript(lines: lines, duration: end, isAutoGenerated: false, language: payload.lang ?? preferredLanguage)
    }

    // MARK: Wire format

    /// `{ "content": [ { "text", "offset" (ms), "duration" (ms), "lang" } ], "lang", "availableLangs" }`.
    nonisolated struct Payload: Decodable {
        struct Segment: Decodable {
            let text: String
            let offset: Double
            let duration: Double?
            let lang: String?
        }
        let content: [Segment]
        let lang: String?
        let availableLangs: [String]?
    }

    /// Collapse cue-sized segments into ~8 second lines so the prompt stays small.
    nonisolated static func lines(from segments: [Payload.Segment], secondsPerLine: Double) -> [TranscriptLine] {
        var lines: [TranscriptLine] = []
        var bucketStart: Double?
        var buffer: [String] = []
        for segment in segments.sorted(by: { $0.offset < $1.offset }) {
            let text = segment.text.replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { continue }
            let start = segment.offset / 1000
            if bucketStart == nil { bucketStart = start }
            buffer.append(text)
            if start - (bucketStart ?? 0) >= secondsPerLine {
                lines.append(TranscriptLine(start: bucketStart ?? 0, text: buffer.joined(separator: " ")))
                buffer.removeAll()
                bucketStart = nil
            }
        }
        if let start = bucketStart, !buffer.isEmpty {
            lines.append(TranscriptLine(start: start, text: buffer.joined(separator: " ")))
        }
        return lines
    }

    nonisolated private static func errorMessage(from data: Data) -> String {
        struct Envelope: Decodable { let error: String?; let message: String?; let details: String? }
        if let env = try? JSONDecoder().decode(Envelope.self, from: data) {
            let parts = [env.error, env.message, env.details].compactMap { $0 }
            if !parts.isEmpty { return parts.joined(separator: ": ") }
        }
        return String(decoding: data.prefix(200), as: UTF8.self)
    }
}

/// Tries providers in order and reports every failure when none works.
struct FirstWorkingTranscriptProvider: TranscriptProvider {
    var providers: [any TranscriptProvider]

    func transcript(for videoID: String) async throws -> FetchedTranscript {
        var reasons: [String] = []
        for provider in providers {
            do {
                return try await provider.transcript(for: videoID)
            } catch is CancellationError {
                throw CancellationError()
            } catch {
                reasons.append(error.localizedDescription)
            }
        }
        throw RecipeSourceError.transcriptUnavailable(reasons.joined(separator: " Then: "))
    }
}
