import Foundation

/// A transcript fetched for a video, so the cook doesn't have to paste one.
nonisolated struct FetchedTranscript: Sendable, Equatable {
    var lines: [TranscriptLine]
    /// Video length in seconds when the provider knows it.
    var duration: Double?
    var isAutoGenerated: Bool
    var language: String
}

/// Fetches a timestamped transcript for a video. Tried before asking the cook to paste one.
@MainActor
protocol TranscriptProvider {
    func transcript(for videoID: String) async throws -> FetchedTranscript
}

/// YouTube's own caption tracks (manual or auto-generated), read the way the web player does:
/// the watch page carries the InnerTube key, the player endpoint lists the caption tracks, and a
/// track URL returns timed text with per-word timings. No API key; public videos only. This is
/// unofficial, so it can stop working when YouTube changes its page, and the error then tells
/// the cook to paste the transcript instead.
struct YouTubeCaptionsTranscriptProvider: TranscriptProvider {
    var session: URLSession = .shared
    var preferredLanguages = ["en"]
    var segmenter = CaptionSegmenter()

    nonisolated static var playerContext: [String: Any] { ["client": ["clientName": "ANDROID", "clientVersion": "20.10.38"]] }

    func transcript(for videoID: String) async throws -> FetchedTranscript {
        let html = try await fetch(YouTubeLink.watchURL(for: videoID), body: nil)
        guard let key = Self.innertubeKey(in: String(decoding: html, as: UTF8.self)) else {
            throw RecipeSourceError.transcriptUnavailable("YouTube changed its page layout")
        }
        let player = try await fetch(Self.playerEndpoint(key: key), body: Self.playerBody(videoID: videoID))
        let listing = try Self.pickTrack(from: player, preferred: preferredLanguages)
        let timed = try await fetch(listing.track.url, body: nil)
        let cues = try Self.parseTimedText(timed)
        let lines = segmenter.lines(from: cues)
        guard !lines.isEmpty else { throw RecipeSourceError.transcriptUnavailable("the captions are empty") }
        return FetchedTranscript(lines: lines, duration: listing.duration,
                                 isAutoGenerated: listing.track.isGenerated, language: listing.track.languageCode)
    }

    private func fetch(_ url: URL, body: Data?) async throws -> Data {
        var request = URLRequest(url: url)
        request.setValue("en-US", forHTTPHeaderField: "Accept-Language")
        if let body {
            request.httpMethod = "POST"
            request.httpBody = body
            request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        }
        let data: Data
        let response: URLResponse
        do { (data, response) = try await session.data(for: request) }
        catch { throw RecipeSourceError.transcriptUnavailable(error.localizedDescription) }
        let status = (response as? HTTPURLResponse)?.statusCode ?? 0
        guard status == 200 else { throw RecipeSourceError.transcriptUnavailable("YouTube answered HTTP \(status)") }
        return data
    }

    // MARK: Pure pieces (unit-tested with canned responses)

    nonisolated struct CaptionTrack: Sendable, Equatable {
        var url: URL
        var languageCode: String
        var name: String
        var isGenerated: Bool
        var isTranslatable: Bool
    }

    nonisolated struct TrackListing: Sendable, Equatable {
        var track: CaptionTrack
        var duration: Double?
    }

    nonisolated static func innertubeKey(in html: String) -> String? {
        let regex = try! NSRegularExpression(pattern: #""INNERTUBE_API_KEY":\s*"([A-Za-z0-9_-]+)""#)
        guard let m = regex.firstMatch(in: html, range: NSRange(html.startIndex..., in: html)),
              let r = Range(m.range(at: 1), in: html) else { return nil }
        return String(html[r])
    }

    nonisolated static func playerEndpoint(key: String) -> URL {
        URL(string: "https://www.youtube.com/youtubei/v1/player?key=\(key)")!
    }

    nonisolated static func playerBody(videoID: String) -> Data {
        try! JSONSerialization.data(withJSONObject: ["context": playerContext, "videoId": videoID], options: [.sortedKeys])
    }

    /// The best caption track in the player response: a preferred language, manual over
    /// auto-generated; else any track YouTube can translate into the first preferred language.
    nonisolated static func pickTrack(from data: Data, preferred: [String]) throws -> TrackListing {
        guard let root = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw RecipeSourceError.transcriptUnavailable("unexpected reply from YouTube")
        }
        let playability = root["playabilityStatus"] as? [String: Any]
        let status = playability?["status"] as? String ?? "OK"
        if status != "OK" {
            let reason = playability?["reason"] as? String
            switch status {
            case "LOGIN_REQUIRED": throw RecipeSourceError.transcriptUnavailable(reason ?? "the video needs a sign-in (age-restricted?)")
            default: throw RecipeSourceError.transcriptUnavailable(reason ?? "the video is unavailable")
            }
        }
        let duration = ((root["videoDetails"] as? [String: Any])?["lengthSeconds"] as? String).flatMap(Double.init)
        let raw = ((root["captions"] as? [String: Any])?["playerCaptionsTracklistRenderer"] as? [String: Any])?["captionTracks"] as? [[String: Any]] ?? []
        let tracks: [CaptionTrack] = raw.compactMap { t in
            guard let base = t["baseUrl"] as? String, let url = URL(string: base) else { return nil }
            let name = (t["name"] as? [String: Any])
            let label = name?["simpleText"] as? String
                ?? ((name?["runs"] as? [[String: Any]])?.first?["text"] as? String) ?? ""
            return CaptionTrack(url: url, languageCode: t["languageCode"] as? String ?? "",
                                name: label, isGenerated: (t["kind"] as? String) == "asr",
                                isTranslatable: t["isTranslatable"] as? Bool ?? false)
        }
        guard !tracks.isEmpty else { throw RecipeSourceError.transcriptUnavailable("this video has no captions") }

        for language in preferred {
            let matches = tracks.filter { $0.languageCode.lowercased().hasPrefix(language.lowercased()) }
            if let best = matches.first(where: { !$0.isGenerated }) ?? matches.first {
                return TrackListing(track: best, duration: duration)
            }
        }
        if let target = preferred.first, let translatable = tracks.first(where: \.isTranslatable),
           var components = URLComponents(url: translatable.url, resolvingAgainstBaseURL: false) {
            components.queryItems = (components.queryItems ?? []) + [URLQueryItem(name: "tlang", value: target)]
            var track = translatable
            track.url = components.url ?? translatable.url
            track.languageCode = target
            return TrackListing(track: track, duration: duration)
        }
        return TrackListing(track: tracks[0], duration: duration)
    }

    /// One caption cue. `words` carries per-word offsets (seconds from `start`) when the track has them.
    nonisolated struct CaptionCue: Sendable, Equatable {
        var start: Double
        var duration: Double
        var text: String
        var words: [(offset: Double, text: String)]

        static func == (a: CaptionCue, b: CaptionCue) -> Bool {
            a.start == b.start && a.duration == b.duration && a.text == b.text
                && a.words.map(\.offset) == b.words.map(\.offset) && a.words.map(\.text) == b.words.map(\.text)
        }
    }

    /// Parses YouTube timed text: the srv3 format (`<p t d><s t>word</s></p>`, milliseconds) the
    /// player uses, or the older `<text start dur>` format (seconds).
    nonisolated static func parseTimedText(_ data: Data) throws -> [CaptionCue] {
        let reader = TimedTextReader()
        let parser = XMLParser(data: data)
        parser.delegate = reader
        guard parser.parse() || !reader.cues.isEmpty else {
            throw RecipeSourceError.transcriptUnavailable("the captions couldn't be read")
        }
        return reader.cues.filter { !$0.text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
    }
}

/// XMLParser delegate for both timed-text formats. Plain class: the parser calls it synchronously.
nonisolated private final class TimedTextReader: NSObject, XMLParserDelegate {
    var cues: [YouTubeCaptionsTranscriptProvider.CaptionCue] = []
    private var current: YouTubeCaptionsTranscriptProvider.CaptionCue?
    private var currentWordOffset: Double?
    private var currentWordText = ""
    private var inWord = false

    func parser(_ parser: XMLParser, didStartElement element: String, namespaceURI: String?, qualifiedName: String?, attributes: [String: String] = [:]) {
        switch element {
        case "p":
            guard let t = attributes["t"].flatMap(Double.init) else { return }
            let d = attributes["d"].flatMap(Double.init) ?? 0
            current = .init(start: t / 1000, duration: d / 1000, text: "", words: [])
        case "text":
            guard let start = attributes["start"].flatMap(Double.init) else { return }
            let dur = attributes["dur"].flatMap(Double.init) ?? 0
            current = .init(start: start, duration: dur, text: "", words: [])
        case "s":
            inWord = true
            currentWordOffset = (attributes["t"].flatMap(Double.init) ?? 0) / 1000
            currentWordText = ""
        default:
            break
        }
    }

    func parser(_ parser: XMLParser, foundCharacters string: String) {
        guard current != nil else { return }
        if inWord { currentWordText += string } else { current?.text += string }
    }

    func parser(_ parser: XMLParser, didEndElement element: String, namespaceURI: String?, qualifiedName: String?) {
        switch element {
        case "s":
            inWord = false
            if let offset = currentWordOffset {
                current?.words.append((offset: offset, text: currentWordText))
                current?.text += currentWordText
            }
        case "p", "text":
            if var cue = current {
                cue.text = cue.text.replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespaces)
                cues.append(cue)
            }
            current = nil
        default:
            break
        }
    }
}

/// Re-cuts caption cues into sentence-sized lines with tight timestamps. Auto-captions arrive as
/// 2-5 second chunks cut mid-sentence; with word timings we can start each line exactly where
/// its first word is spoken, and break at sentence ends and silences.
nonisolated struct CaptionSegmenter: Sendable {
    var maxSeconds: Double = 8
    var maxWords = 22
    var minSecondsBeforeSentenceBreak: Double = 2.5
    var silenceGap: Double = 1.2

    private static let stageDirection = try! NSRegularExpression(pattern: #"^\s*[\[\(][^\]\)]*[\]\)]\s*$"#)

    func lines(from cues: [YouTubeCaptionsTranscriptProvider.CaptionCue]) -> [TranscriptLine] {
        // Flatten to (time, end, text) words; a cue without word timings is one "word" at the
        // cue start. `end` is when speech stops: the next word's start, or the cue's end for its
        // last word, so a pause is measured from where the previous words actually finished.
        var words: [(time: Double, end: Double, text: String)] = []
        for cue in cues {
            let text = cue.text.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty, !Self.isStageDirection(text) else { continue }
            let cueEnd = cue.start + max(cue.duration, 0)
            if cue.words.isEmpty {
                words.append((cue.start, cueEnd, text))
            } else {
                let timed = cue.words.compactMap { w -> (Double, String)? in
                    let t = w.text.trimmingCharacters(in: .whitespacesAndNewlines)
                    return t.isEmpty || Self.isStageDirection(t) ? nil : (cue.start + w.offset, t)
                }
                for (i, w) in timed.enumerated() {
                    let end = i + 1 < timed.count ? timed[i + 1].0 : max(cueEnd, w.0)
                    words.append((w.0, end, w.1))
                }
            }
        }

        var lines: [TranscriptLine] = []
        var buffer: [(time: Double, end: Double, text: String)] = []
        func flush() {
            guard let first = buffer.first else { return }
            lines.append(TranscriptLine(start: first.time, text: buffer.map(\.text).joined(separator: " ")))
            buffer.removeAll(keepingCapacity: true)
        }
        var lastEnd = -Double.infinity
        for word in words {
            if !buffer.isEmpty, word.time - lastEnd > silenceGap { flush() }
            buffer.append(word)
            lastEnd = word.end
            let span = word.time - (buffer.first?.time ?? word.time)
            let endsSentence = word.text.last.map { ".?!".contains($0) } ?? false
            if buffer.count >= maxWords || span >= maxSeconds
                || (endsSentence && (span >= minSecondsBeforeSentenceBreak || buffer.count >= 6)) {
                flush()
            }
        }
        flush()
        return lines
    }

    private static func isStageDirection(_ text: String) -> Bool {
        stageDirection.firstMatch(in: text, range: NSRange(text.startIndex..., in: text)) != nil
    }
}
