import Foundation
import Testing
@testable import CookAlong

@MainActor
struct TranscriptProviderTests {
    typealias Provider = YouTubeCaptionsTranscriptProvider

    @Test func findsTheInnertubeKeyInTheWatchPage() {
        let html = #"<script>ytcfg.set({"INNERTUBE_API_KEY":"AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8","INNERTUBE_CLIENT_NAME":"WEB"});</script>"#
        #expect(Provider.innertubeKey(in: html) == "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8")
        #expect(Provider.innertubeKey(in: "<html>no key here</html>") == nil)
        #expect(Provider.playerEndpoint(key: "K").absoluteString == "https://www.youtube.com/youtubei/v1/player?key=K")
        let body = try? JSONSerialization.jsonObject(with: Provider.playerBody(videoID: "NTpzPZajtEU")) as? [String: Any]
        #expect(body?["videoId"] as? String == "NTpzPZajtEU")
        #expect(((body?["context"] as? [String: Any])?["client"] as? [String: Any])?["clientName"] as? String == "ANDROID")
    }

    private func player(tracks: [[String: Any]], status: String = "OK", reason: String? = nil, length: String? = "889") -> Data {
        var root: [String: Any] = ["playabilityStatus": ["status": status, "reason": reason as Any].compactMapValues { $0 is String ? $0 : nil }]
        if let length { root["videoDetails"] = ["title": "Ramen", "lengthSeconds": length] }
        if !tracks.isEmpty { root["captions"] = ["playerCaptionsTracklistRenderer": ["captionTracks": tracks]] }
        return try! JSONSerialization.data(withJSONObject: root)
    }

    private func track(_ lang: String, generated: Bool = false, translatable: Bool = true) -> [String: Any] {
        ["baseUrl": "https://www.youtube.com/api/timedtext?v=x&lang=\(lang)" + (generated ? "&kind=asr" : ""),
         "languageCode": lang, "isTranslatable": translatable,
         "name": ["runs": [["text": generated ? "\(lang) (auto-generated)" : lang]]]] .merging(generated ? ["kind": "asr"] : [:]) { a, _ in a }
    }

    @Test func prefersManualEnglishOverAutoGenerated() throws {
        let listing = try Provider.pickTrack(from: player(tracks: [track("en", generated: true), track("en"), track("de")]), preferred: ["en"])
        #expect(listing.track.languageCode == "en")
        #expect(!listing.track.isGenerated)
        #expect(listing.duration == 889)
    }

    @Test func takesAutoGeneratedWhenThatIsAllThereIs() throws {
        let listing = try Provider.pickTrack(from: player(tracks: [track("en-US", generated: true)]), preferred: ["en"])
        #expect(listing.track.isGenerated)
        #expect(listing.track.languageCode == "en-US")
        #expect(listing.track.name == "en-US (auto-generated)")
    }

    @Test func translatesWhenNoPreferredLanguageExists() throws {
        let listing = try Provider.pickTrack(from: player(tracks: [track("ko", translatable: true)]), preferred: ["en"])
        #expect(listing.track.languageCode == "en")
        #expect(listing.track.url.query?.contains("tlang=en") == true)
    }

    @Test func reportsMissingCaptionsAndUnplayableVideos() {
        #expect(throws: RecipeSourceError.transcriptUnavailable("this video has no captions")) {
            try Provider.pickTrack(from: player(tracks: []), preferred: ["en"])
        }
        #expect(throws: RecipeSourceError.transcriptUnavailable("Sign in to confirm your age")) {
            try Provider.pickTrack(from: player(tracks: [], status: "LOGIN_REQUIRED", reason: "Sign in to confirm your age"), preferred: ["en"])
        }
        #expect(throws: RecipeSourceError.transcriptUnavailable("unexpected reply from YouTube")) {
            try Provider.pickTrack(from: Data("<html>".utf8), preferred: ["en"])
        }
        #expect(RecipeSourceError.transcriptUnavailable("x").errorDescription?.contains("Show transcript") == true)
        #expect(RecipeSourceError.transcriptUnavailable("x").errorDescription?.contains("GEMINI_API_KEY") == true)
    }

    static let srv3 = """
    <?xml version="1.0" encoding="utf-8" ?><timedtext format="3">
    <head><ws id="0"/><wp id="0"/></head>
    <body>
    <w t="0" id="1" wp="1" ws="1"/>
    <p t="80" d="3160" w="1"><s ac="0">Hi</s><s t="240" ac="0"> everyone.</s><s t="800" ac="0"> Welcome</s><s t="1200" ac="0"> to</s><s t="1520" ac="0"> Make</s><s t="1840" ac="0"> It</s></p>
    <p t="3230" d="10" w="1" a="1">
    </p>
    <p t="3240" d="1760" w="1"><s ac="0">Wednesday.</s></p>
    <p t="5000" d="2000" w="1"><s ac="0">[Music]</s></p>
    <p t="8000" d="3000" w="1"><s ac="0">So</s><s t="500" ac="0"> put</s><s t="900" ac="0"> the</s><s t="1200" ac="0"> water</s><s t="1600" ac="0"> on</s><s t="2400" ac="0"> &amp; salt it.</s></p>
    </body>
    </timedtext>
    """

    @Test func parsesSrv3WithWordTimings() throws {
        let cues = try Provider.parseTimedText(Data(Self.srv3.utf8))
        #expect(cues.count == 4)
        #expect(cues[0].start == 0.08)
        #expect(cues[0].duration == 3.16)
        #expect(cues[0].text == "Hi everyone. Welcome to Make It")
        #expect(cues[0].words.map(\.offset) == [0, 0.24, 0.8, 1.2, 1.52, 1.84])
        #expect(cues[3].text == "So put the water on & salt it.")
    }

    @Test func parsesTheLegacyTranscriptFormat() throws {
        let xml = #"<?xml version="1.0" encoding="utf-8" ?><transcript><text start="0.08" dur="3.16">Hi everyone &amp; welcome</text><text start="3.24" dur="1.76">to Make It Wednesday.</text></transcript>"#
        let cues = try Provider.parseTimedText(Data(xml.utf8))
        #expect(cues.map(\.start) == [0.08, 3.24])
        #expect(cues[0].text == "Hi everyone & welcome")
        #expect(cues[0].words.isEmpty)
    }

    @Test func segmenterStartsLinesOnTheSpokenWordAndDropsMusic() throws {
        let cues = try Provider.parseTimedText(Data(Self.srv3.utf8))
        let lines = CaptionSegmenter().lines(from: cues)
        // "Hi everyone." breaks at the sentence end ... no: too short (< 2.5 s and < 6 words); the
        // sentence closes at "Wednesday." (3.24 s), then a silence gap before "So put the water on".
        #expect(lines.map(\.text) == ["Hi everyone. Welcome to Make It Wednesday.", "So put the water on & salt it."])
        #expect(lines.map(\.start) == [0.08, 8.0])
    }

    @Test func segmenterHandlesCuesWithoutWordTimings() {
        let cues = [
            Provider.CaptionCue(start: 10, duration: 3, text: "Now the garlic, thin slices.", words: []),
            Provider.CaptionCue(start: 13, duration: 3, text: "They turn golden evenly.", words: []),
            Provider.CaptionCue(start: 30, duration: 2, text: "Water's boiling.", words: []),
        ]
        let lines = CaptionSegmenter().lines(from: cues)
        #expect(lines.map(\.start) == [10, 30])
        #expect(lines[0].text == "Now the garlic, thin slices. They turn golden evenly.")
    }
}
